<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Vintageous Command Line</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.excmdline</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.excmdline</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.excmdline</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.excmdline</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(:)(?:(\d+)|(cd(?:d)?|w(?:rite|q|all)?|e(?:dit|new|xit)?|pw(?:d)?|buffers|files|ls|reg(?:isters)?|map|ab(?:breviate)?|q(:?uit|all)?|r(?:ead)?|as(?:cii)?|f(?:ile)?|move|co(?:py)?|t(?:abfirst|abprev|abedit|abe|abnext|abn|ablast|abl|abonly|abo)?|setl(:?ocal)?|se(?:t)?|s(?:ubstitute|hell|h)?|&amp;&amp;|d(?:elete)?|g(?:lobal)?|p(?:rint)?|P(?:rint)?|bro(?:owse)?|cq(?:uit)?|x(?:it)?|on(?:ly)?|new|y(?:ank)?|(?:un)?vs(?:plit)?)(!)?)?</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.excmdline</string>
	<key>uuid</key>
	<string>eb9bb9a2-ab05-4edf-aee1-22d79cc9d9b0</string>
</dict>
</plist>
